### ISSUE TITLE
Teensy support

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [apla/brackets-cuwire#11]
it would be very nice to have also teensy support in cuwire.
There is an existing library and definition for arduino:
http://www.pjrc.com/teensy/teensyduino.html

Here is an overview of the pins out:
http://www.pjrc.com/teensy/pinout.html

I don't know how hard it is to add teensy support >> but it would be awesome!!! :+1: 
Thx for sharing this great plugin with us

**Comment by apla** [comment]
Have you tried? I added teensy support few weeks ago, but not tested it. Please share your result if you brave enough for test -)

**Comment by apla** [comment]
Forgot to mention: cuwire supports Arduino IDE 1.5.x or later. Teensyduino is actually patch for Arduino IDE. So, You will need to install Arduino IDE 1.6.1 (or another latest version), then install Teensyduino 1.21 or later and try.

**Comment by Jorgen-VikingGod** [comment]
good to know; but I have still issues.
Arduino IDE: 1.61 for Java 7+
Tinsyduino: 1.21
Brackets: 1.2 build 1.2.0-15697 (release 8f82e2a97)
working on Mac 10.10.2

Issue:
no teensy loader was shown and also compile is always "Failed"
but in Arduino IDE it works fine - perhaps something with paths and library access?

some hints:
serial monitor is working fine.
so the error should have to do something with the arduino compiler.
I have my arduino.app not in my default application folder (perhaps this could be the problem?)
-> but I select my application folder under settings of cuwire

**Comment by apla** [comment]
Do you have any compilation errors? Or status label just changes color?

**Comment by Jorgen-VikingGod** [comment]
sorry, was on vacations...
Only the status label changed the color and said "Failed"

**Comment by Jorgen-VikingGod** [comment]
![image](https://cloud.githubusercontent.com/assets/6171589/7052158/25144634-de2d-11e4-86ff-bdcf67566a3b.png)

This is what I'm seeing...
Configuration by default:
![image](https://cloud.githubusercontent.com/assets/6171589/7052178/42e40366-de2d-11e4-9573-46c4b23fd4e7.png)

On arduino.app there comes up a "teensy.app" for flashing the teensy board.
This was installed by teensyduino...
After installation there are some libraries and hardware definition (for teensy2, 3, LC) and if course the "programmer"

But on cuwire I can not select a programmer - could this be the problem?

thx for your work.
Hope you can fin the error...

**Comment by apla** [comment]
I found that bug a week ago and in a few days I'm going to test a new version, and also will give you to try it. I hope your problem will be fixed with it.

P.S.: Seems cuwire looks really bad in dark.

**Comment by Jorgen-VikingGod** [comment]
wow, great to hear!
And yes the comboboxes are bad to read.

Really looking forward to your fixes
